2024-10-17 14:52:09.755 [info] WARNING:pygls.protocol:Cancel notification for unknown message id "8"

2024-10-17 15:05:28.023 [info] ERROR:pygls.protocol:Failed to handle request 24 textDocument/documentHighlight DocumentHighlightParams(text_document=TextDocumentIdentifier(uri='file:///home/lucky/Documents/classes/advanced_dbs/assignment1/P1_GX_Nombre_Apellidos-Nombre-Apellidos/ODM.py'), position=22:40, work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight
    names = jedi_script.get_references(*jedi_lines, scope="file")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (40) is not in a valid range (0-28) for line 23 ('    required_vars : set[str]\r\n').

2024-10-17 15:05:28.036 [info] [Error - 3:05:28 PM] Request textDocument/documentHighlight failed.
2024-10-17 15:05:28.036 [info]   Message: ValueError: `column` parameter (40) is not in a valid range (0-28) for line 23 ('    required_vars : set[str]\r\n').
  Code: -32602 
{'traceback': ['  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight\n    names = jedi_script.get_references(*jedi_lines, scope="file")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2024-10-17 15:06:10.158 [info] ERROR:pygls.protocol:Failed to handle request 32 textDocument/documentHighlight DocumentHighlightParams(text_document=TextDocumentIdentifier(uri='file:///home/lucky/Documents/classes/advanced_dbs/assignment1/P1_GX_Nombre_Apellidos-Nombre-Apellidos/ODM.py'), position=22:40, work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight
    names = jedi_script.get_references(*jedi_lines, scope="file")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (40) is not in a valid range (0-14) for line 23 ('    ----------\r\n').

2024-10-17 15:06:10.159 [info] [Error - 3:06:10 PM] Request textDocument/documentHighlight failed.
2024-10-17 15:06:10.159 [info]   Message: ValueError: `column` parameter (40) is not in a valid range (0-14) for line 23 ('    ----------\r\n').
  Code: -32602 
{'traceback': ['  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight\n    names = jedi_script.get_references(*jedi_lines, scope="file")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2024-10-17 15:06:56.130 [info] ERROR:pygls.protocol:Failed to handle request 35 textDocument/documentHighlight DocumentHighlightParams(text_document=TextDocumentIdentifier(uri='file:///home/lucky/Documents/classes/advanced_dbs/assignment1/P1_GX_Nombre_Apellidos-Nombre-Apellidos/ODM.py'), position=22:40, work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight
    names = jedi_script.get_references(*jedi_lines, scope="file")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (40) is not in a valid range (0-14) for line 23 ('    Attributes\r\n').

2024-10-17 15:06:56.130 [info] [Error - 3:06:56 PM] Request textDocument/documentHighlight failed.
2024-10-17 15:06:56.130 [info]   Message: ValueError: `column` parameter (40) is not in a valid range (0-14) for line 23 ('    Attributes\r\n').
  Code: -32602 
{'traceback': ['  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight\n    names = jedi_script.get_references(*jedi_lines, scope="file")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
2024-10-17 15:10:58.659 [info] ERROR:pygls.protocol:Failed to handle request 38 textDocument/documentHighlight DocumentHighlightParams(text_document=TextDocumentIdentifier(uri='file:///home/lucky/Documents/classes/advanced_dbs/assignment1/P1_GX_Nombre_Apellidos-Nombre-Apellidos/ODM.py'), position=22:40, work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight
    names = jedi_script.get_references(*jedi_lines, scope="file")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (40) is not in a valid range (0-28) for line 23 ('    required_vars : set[str]\r\n').

2024-10-17 15:10:58.660 [info] [Error - 3:10:58 PM] Request textDocument/documentHighlight failed.
2024-10-17 15:10:58.660 [info]   Message: ValueError: `column` parameter (40) is not in a valid range (0-28) for line 23 ('    required_vars : set[str]\r\n').
  Code: -32602 
{'traceback': ['  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 364, in highlight\n    names = jedi_script.get_references(*jedi_lines, scope="file")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/lucky/.vscode-oss/extensions/ms-python.python-2024.16.1-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
